### ISSUE TITLE
Revive node-navigator project?

### ISSUE THREAD

**Issue by jcbhmr** [CesiumLabs/.github#1]
Hello @CesiumLabs! 👋

I'd be interested in reviving the https://github.com/CesiumLabs/node-navigator project! I'd love to contribute some code to add support for the storage interface https://developer.mozilla.org/en-US/docs/Web/API/Navigator/storage to see how much disk space is available on the global OS.

Some other specs that I'd be interested in adding to the project are https://wicg.github.io/webusb/ and https://w3c.github.io/battery/#dom-navigator-getbattery

Sorry if this is the wrong place to ask. The main repo is archived. 🤷‍♀️

cc @skdhg since you are the author of that module

**Comment by twlite** [comment]
> Hello @CesiumLabs! 👋
> 
> I'd be interested in reviving the https://github.com/CesiumLabs/node-navigator project! I'd love to contribute some code to add support for the storage interface https://developer.mozilla.org/en-US/docs/Web/API/Navigator/storage to see how much disk space is available on the global OS.
> 
> Some other specs that I'd be interested in adding to the project are https://wicg.github.io/webusb/ and https://w3c.github.io/battery/#dom-navigator-getbattery
> 
> Sorry if this is the wrong place to ask. The main repo is archived. 🤷‍♀️
> 
> cc @skdhg since you are the author of that module

sure, I have unarchived the repo and transferred it into my account since this org is no longer active.

**Comment by jcbhmr** [comment]
Awesome! 🎉 Thanks for re-opening the project! 😊 I've opened some issues to communicate what I think are things to improve or add (and of course get feedback and discuss them 😉). I hope to open PRs as well for some of the things I mentioned above too! ❤️

Closing this issue as you've answered my question. Thanks! ❤️
